### ISSUE TITLE
Generating image output as in Figure 3 of the paper

### ISSUE THREAD

**Issue by mcm2020** [applied-ai-lab/genesis#1]
Hi, I am trying to generate images such as those in figure 3 of the paper. That is, a way to see the component-by-component scene generation for a single input image with genesis. However, the only script I see that creates and saves images is compute_fid.py.

I ran compute_fid.py on the Multi-dSprites dataset, but its output is a single image (all of the components together) for every input image.

Is there a way to generate the component-by-component output? Thanks.

**Comment by martinengelcke** [comment]
Hi,

Thank you for your interest!

I added a script for visualising the component-by-component scene generation (https://github.com/applied-ai-lab/genesis/blob/master/scripts/visualise_generation.py). This could be modified to save pngs to file, etc.

Hope this helps!

Best,
Martin

**Comment by mcm2020** [comment]
Thanks!
