### ISSUE TITLE
training dataset size?

### ISSUE THREAD

**Issue by huangqinwen** [applied-ai-lab/genesis#12]
Hi, I'm wondering how will the size of training dataset affect the performance of Genesis v2? Does it require a large amount of data to train? (all datasets seem to have > 10000 images)

**Comment by martinengelcke** [comment]
Hello @huangq1995, I have not tried training Genesis-v2 on smaller datasets. I suspect that it would be difficult to get decent samples, but segmentations might still be ok

**Comment by huangqinwen** [comment]
Thank you!
