### ISSUE TITLE
Unable to download APC dataset

### ISSUE THREAD

**Issue by Buzz-Beater** [applied-ai-lab/genesis#13]
Hi,

I was trying to reproduce your results on APC dataset and I found the link provided seems to be outdated (permission denied). Is there any chance you can provide an available download link for APC? Thanks!

**Comment by martinengelcke** [comment]
Hi @Buzz-Beater,

Thanks for flagging this. I have reached out to the creators of the dataset and asked them whether they could fix the download link. I will update this issue accordingly.

Best,
Martin

**Comment by martinengelcke** [comment]
The dataset authors fixed the link. I am going to close this issue, but feel free to re-open if you still encounter problems.
