### ISSUE TITLE
Computation of iou

### ISSUE THREAD

**Issue by YugeTen** [applied-ai-lab/genesis#14]
Hi all,

Thank you for releasing your code! I have a question regarding the computation of IOU [here](https://github.com/applied-ai-lab/genesis/blob/05798c379eb725aed53032ff17993bb984e1a9b2/utils/misc.py#L162). As we know IOU is computed as follows:
> IOU = area of overlap/area of union = TP/(TP+FP+FN)

However in your code it is computed as:
> IOU' = area of overlap/total number of pixels = TP/(TP*2+FP+FN)

Perhaps I missed something or am unfamiliar with the segmentation metrics in the literature, could you please help me understand why it is implemented this way?

**References:**
1. https://towardsdatascience.com/metrics-to-evaluate-your-semantic-segmentation-model-6bcb99639aa2
2. https://stats.stackexchange.com/questions/273537/f1-dice-score-vs-iou/276144#276144

**Comment by martinengelcke** [comment]
Hi @YugeTen ,

`mask_A` and `mask_B` are (strictly) assumed to be boolean tensors as indicated by the assert statements when `debug = True`. The IOU is therefore computed in the standard way as `TP/(TP+FP+FN)`.

Hope this clarifies what's going on, but let me know in case there is still any uncertainty.

Best,
Martin

**Comment by martinengelcke** [comment]
PS: I pushed 9abf202bbad6fa4a675117fdea0be163e4f16695 so that shape & type checks are always applied when the function is used.

**Comment by YugeTen** [comment]
Ah right thank you, that does make sense!
