### ISSUE TITLE
Handle grayscale input images

### ISSUE THREAD

**Issue by mttgdd** [applied-ai-lab/genesis#3]
Hi,
The genesis model does not seem to work with single-channel input images.
Would it be a simple matter to tweak the architecture to allow this?

**Comment by martinengelcke** [comment]
The model should already supports this:
https://github.com/applied-ai-lab/genesis/blob/8463af1a4ec7c36c531a99dc3e7c7871d80625d4/models/genesis_config.py#L76

You can define an "input_channels" flag with value "1" in your custom data loader for single-channel images. If the flag is not defined, then the model defaults to three input channels.

Let me know if this works for you :)

**Comment by martinengelcke** [comment]
Marking this as closed. Feel free to re-open if the solution above does not work.
