### ISSUE TITLE
Shapestacks unavailable

### ISSUE THREAD

**Issue by pfabreu** [applied-ai-lab/genesis#7]
I cannot currently download the Shapestacks dataset files at https://shapestacks.robots.ox.ac.uk/static/download/v1/shapestacks-rgb.tar.gz for example. I am not sure if this is only my issue, but I've tried it with all the settings I could.

**Comment by martinengelcke** [comment]
Hi @pedro-abreu,

Thanks a lot for flagging this up. I can confirm that I am also unable to download the ShapeStacks files from the website. I am going to inquire what's going on over there and will get back to you.

Best,
Martin

**Comment by pfabreu** [comment]
It's available now! Thanks :) I'm closing the issue.

**Comment by dsvilarkovic** [comment]
I still wasn't able to download from urls shown in **utils/shapestacks_urls.txt**, but if you switch from shapestacks to shapestacks-file it works (and it's even like that on the https://ogroth.github.io/shapestacks/ page) i.e.:
from 
`wget https://shapestacks.robots.ox.ac.uk/static/download/v1/shapestacks-rgb.tar.gz`
to
`wget https://shapestacks-file.robots.ox.ac.uk/static/download/v1/shapestacks-rgb.tar.gz`

**Comment by martinengelcke** [comment]
Hi @dsvilarkovic,

Thanks for spotting this. I pushed a fix in eb09c272184380fabd4c422dcde74b6fa66e992e.

Best,
Martin
